services:
  - type: web
    name: stnc-ai-frontend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://stns-ai.onrender.com/api
